const contactperpage =[
    {
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },
  {
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },
  { Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },
  { 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },
  { 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },
  { 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },{ 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },{ 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },{ 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },{ 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },{ 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },{ 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  },{ 
    Name:"krishna",
    Designation:"developer",
    Company:"tcs",
    Industry:"it",
    PhoneNumber:"9877649228",
    Country:"india",
    Email:"krishna@gmail.com"
  }
];

export default contactperpage;